const medicineActionTypes = {
    ADD_MEDICINE: 'ADD_MEDICINE',
    REMOVE_MEDICINE: 'REMOVE_MEDICINE',
    ADD_OPTION_MEDICINE: 'ADD_OPTION_MEDICINE',
    REMOVE_OPTION_MEDICINE: 'REMOVE_OPTION_MEDICINE',
    ADD_STOCK: 'ADD_STOCK',
    REMOVE_STOCK: 'REMOVE_STOCK',

}

export default medicineActionTypes;