const userActionTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    ADD_ADMIN: 'ADD_ADMIN',
    ADD_OFFICER: 'ADD_OFFICER',
    ADD_DISTRIBUTOR: 'ADD_DISTRIBUTOR',
    ADD_SELECTED_USER: 'ADD_SELECTED_USER'
}

export default userActionTypes;